# Generated by Django 3.2.25 on 2025-10-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=64, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, max_length=512, null=True)),
                ('foto', models.ImageField(upload_to='mascotas/')),
                ('estado', models.CharField(default='Disponible', max_length=20)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tipomascota')),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.CharField(blank=True, max_length=50, null=True)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.mascota')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.persona')),
            ],
        ),
    ]
